name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: ExamHelper.slnx
      Test_Project_Path: ExamSettings\ExamSettings.csproj
      Wap_Project_Directory: ExamHelper.Package
      Wap_Project_Path: ExamHelper.Package\ExamHelper.Package.wapproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.102

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Execute unit tests
        run: dotnet test

      - name: List directory structure
        run: Get-ChildItem

      - name: Restore the application
        env:
          Configuration: ${{ matrix.configuration }}
        run: |
          msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration

      - name: Decode the pfx
        run: |
          # 确保目标目录存在
          $targetDir = $env:Wap_Project_Directory
          if (-not (Test-Path -Path $targetDir)) {
            New-Item -ItemType Directory -Path $targetDir -Force
          }
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
          $certificatePath = Join-Path -Path $targetDir -ChildPath GitHubActionsWorkflow.pfx
          [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

      - name: Create the app package
        run: |
          msbuild $env:Wap_Project_Path /p:Configuration=${{ matrix.configuration }} /p:UapAppPackagePackageBuildMode=no /n:AppPackages